### PR TITLE
Remove hundreds of duplicated files caused probably by some recursive operation.

### PR DESCRIPTION
**Pull request by ggbecker**
This was making the git directory on local machine slow to navigate.

### CODE REVIEW

**Comment by matejak** [comment]
@wrabcak looks like a SELinux lab exercise issue.

**Comment by ggbecker** [comment]
> @wrabcak looks like a SELinux lab exercise issue.

Note: It's from 2018Labs folder.

**Comment by lkerner** [comment]
@wrabcak , can you take a quick look to confirm that I can merge this PR? Thanks.

**Comment by lkerner** [comment]
@wrabcak : please review

**Comment by wrabcak** [comment]
Yeah, Let's drop it.

**Pull request closed without merging**
