### PR TITLE
Fix the inconsistency in lab2_openscap directory name.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by adelton** [comment]
I've edited the getting-report.png as well -> d56cabe52a388243a7dea0c57e429c7839aa182f.

**Comment by matejak** [comment]
Awesome, I wonder how you have managed to edit the PNG so easily. However, there is `labo` now as the labs directory. Is it possible to fix this?

**Comment by adelton** [comment]
Ah, some unwanted side effect. Fixed -> 8c9291445107461c34bcc5926f6efcca5e6f4296.

**Comment by matejak** [comment]
Great, thanks!

**Pull request merged**
